# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\arinc\Documents\Programming\Python\dicerollgui\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(251, 311)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.d4SpinBox = QtWidgets.QSpinBox(self.centralWidget)
        self.d4SpinBox.setMinimum(1)
        self.d4SpinBox.setObjectName("d4SpinBox")
        self.gridLayout.addWidget(self.d4SpinBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.d6SpinBox = QtWidgets.QSpinBox(self.centralWidget)
        self.d6SpinBox.setMinimum(1)
        self.d6SpinBox.setObjectName("d6SpinBox")
        self.gridLayout.addWidget(self.d6SpinBox, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.d8SpinBox = QtWidgets.QSpinBox(self.centralWidget)
        self.d8SpinBox.setMinimum(1)
        self.d8SpinBox.setObjectName("d8SpinBox")
        self.gridLayout.addWidget(self.d8SpinBox, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.d10SpinBox = QtWidgets.QSpinBox(self.centralWidget)
        self.d10SpinBox.setMinimum(1)
        self.d10SpinBox.setObjectName("d10SpinBox")
        self.gridLayout.addWidget(self.d10SpinBox, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.d12SpinBox = QtWidgets.QSpinBox(self.centralWidget)
        self.d12SpinBox.setMinimum(1)
        self.d12SpinBox.setObjectName("d12SpinBox")
        self.gridLayout.addWidget(self.d12SpinBox, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.d20SpinBox = QtWidgets.QSpinBox(self.centralWidget)
        self.d20SpinBox.setMinimum(1)
        self.d20SpinBox.setObjectName("d20SpinBox")
        self.gridLayout.addWidget(self.d20SpinBox, 5, 1, 1, 1)
        self.d4Label = QtWidgets.QLabel(self.centralWidget)
        self.d4Label.setObjectName("d4Label")
        self.gridLayout.addWidget(self.d4Label, 6, 0, 1, 1)
        self.d4Roll = QtWidgets.QLabel(self.centralWidget)
        self.d4Roll.setAutoFillBackground(False)
        self.d4Roll.setText("")
        self.d4Roll.setObjectName("d4Roll")
        self.gridLayout.addWidget(self.d4Roll, 6, 1, 1, 1)
        self.d6Label = QtWidgets.QLabel(self.centralWidget)
        self.d6Label.setObjectName("d6Label")
        self.gridLayout.addWidget(self.d6Label, 7, 0, 1, 1)
        self.d6Roll = QtWidgets.QLabel(self.centralWidget)
        self.d6Roll.setAutoFillBackground(False)
        self.d6Roll.setText("")
        self.d6Roll.setObjectName("d6Roll")
        self.gridLayout.addWidget(self.d6Roll, 7, 1, 1, 1)
        self.d8Label = QtWidgets.QLabel(self.centralWidget)
        self.d8Label.setObjectName("d8Label")
        self.gridLayout.addWidget(self.d8Label, 8, 0, 1, 1)
        self.d8Roll = QtWidgets.QLabel(self.centralWidget)
        self.d8Roll.setAutoFillBackground(False)
        self.d8Roll.setText("")
        self.d8Roll.setObjectName("d8Roll")
        self.gridLayout.addWidget(self.d8Roll, 8, 1, 1, 1)
        self.d10Label = QtWidgets.QLabel(self.centralWidget)
        self.d10Label.setObjectName("d10Label")
        self.gridLayout.addWidget(self.d10Label, 9, 0, 1, 1)
        self.d10Roll = QtWidgets.QLabel(self.centralWidget)
        self.d10Roll.setAutoFillBackground(False)
        self.d10Roll.setText("")
        self.d10Roll.setObjectName("d10Roll")
        self.gridLayout.addWidget(self.d10Roll, 9, 1, 1, 1)
        self.d12Label = QtWidgets.QLabel(self.centralWidget)
        self.d12Label.setObjectName("d12Label")
        self.gridLayout.addWidget(self.d12Label, 10, 0, 1, 1)
        self.d12Roll = QtWidgets.QLabel(self.centralWidget)
        self.d12Roll.setAutoFillBackground(False)
        self.d12Roll.setText("")
        self.d12Roll.setObjectName("d12Roll")
        self.gridLayout.addWidget(self.d12Roll, 10, 1, 1, 1)
        self.d12Label_2 = QtWidgets.QLabel(self.centralWidget)
        self.d12Label_2.setObjectName("d12Label_2")
        self.gridLayout.addWidget(self.d12Label_2, 11, 0, 1, 1)
        self.d20Roll = QtWidgets.QLabel(self.centralWidget)
        self.d20Roll.setAutoFillBackground(False)
        self.d20Roll.setText("")
        self.d20Roll.setObjectName("d20Roll")
        self.gridLayout.addWidget(self.d20Roll, 11, 1, 1, 1)
        self.rollButton = QtWidgets.QPushButton(self.centralWidget)
        self.rollButton.setObjectName("rollButton")
        self.gridLayout.addWidget(self.rollButton, 12, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "How many d4s?"))
        self.label_2.setText(_translate("MainWindow", "How many d6s?"))
        self.label_3.setText(_translate("MainWindow", "How many d8s?"))
        self.label_4.setText(_translate("MainWindow", "How many d10s?"))
        self.label_5.setText(_translate("MainWindow", "How many d12s?"))
        self.label_6.setText(_translate("MainWindow", "How many d20s?"))
        self.d4Label.setText(_translate("MainWindow", "d4"))
        self.d6Label.setText(_translate("MainWindow", "d6"))
        self.d8Label.setText(_translate("MainWindow", "d8"))
        self.d10Label.setText(_translate("MainWindow", "d10"))
        self.d12Label.setText(_translate("MainWindow", "d12"))
        self.d12Label_2.setText(_translate("MainWindow", "d20"))
        self.rollButton.setText(_translate("MainWindow", "Roll"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
